data_cfg:
  dataset_name: OUMVLP
  dataset_root: ../datasets/OU-MVLP-pkl
  dataset_partition: ./datasets/OUMVLP/OUMVLP.json
  # dataset_partition: ./datasets/OUMVLP/OUMVLP-1000.json
  # dataset_partition: ./datasets/OUMVLP/OUMVLP-300.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: OUMVLP

model_cfg:
  model: BinGait
  backbone_cfg:
    type: ResNet9
    block: BasicBlock
    channels: [64, 128, 256, 512]
    layers: [1, 1, 1, 1]
    strides: [1, 2, 2, 1]
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 5153
    in_channels: 256
    parts_num: 16
  bin_num: [16]
  hash_dim: 512

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 121500
  save_name: BinGait
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered
    frames_all_limit: 720
  metric: hamming
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - type: HashLoss
    loss_term_weight: 1.0
    log_prefix: hash

trainer_cfg:
  enable_float16: true
  fix_BN: true
  sync_BN: true
  restore_ckpt_strict: false
  optimizer_reset: true
  save_name: BinGait

  restore_hint: 120000
  log_iter: 100
  save_iter: 100
  total_iter: 120800

  # restore_hint: 120800
  # log_iter: 100
  # save_iter: 100
  # total_iter: 121500

  with_test: false
  grad_accum_steps: 32
  sampler:
    type: TripletSampler
    sample_type: fixed_unordered
    batch_size: [8, 4]
    frames_num_fixed: 30
    frames_num_max: 40
    frames_num_min: 20
  transform:
    - type: BaseSilCuttingTransform

optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0000005

# optimizer_cfg:
#   lr: 0.0002
#   momentum: 0.9
#   solver: Adam
#   weight_decay: 0.0000005

scheduler_cfg:
  gamma: 0.5
  milestones: [121200]
  scheduler: MultiStepLR
